### PR TITLE
Bug/id 205/log in administrator without authorization

### LINKED ISSUE #205: Login in administrator mode without authorization by omitting code verification in verification screen
**Describe the bug**
When you try to log in in administrator mode and skip the verification by pressing "continue with general user" you are logged in with the functionality of an administrator and can create incidents on the map.

**To Reproduce**

1. Steps to reproduce the behavior:
2. Launch the Hermes application
3. Click on "sign in with google".
4. Select a valid google account
5. Select in the option "Type User" the role "Administrator".
6. Click on "Sign up".
7. Click on "Continue Genereal Account".
8. Click on "Im sure!
9. Click on a street on the map
10.  Note that the incident notification menu is displayed with the general user type or the Hermes application is restarted.

**Expected behavior**
A PopUp should be displayed telling us that the functionality is not allowed for the current user type.

**Attachment**
[Screencast from 29-06-23 19:12:58.webm](https://github.com/CampusDelSaber/hermes/assets/90268595/6fffae85-c2a9-4d1a-b766-a535bbdf12d8)

https://github.com/CampusDelSaber/hermes/assets/90268595/5b9e0b62-bfa0-42ac-a689-d71c6da41f13

**Smartphone :**
 - Device: Pixel 2
 - OS: Android 12

### PR DESCRIPTION
**Pull request by VictorCespedesCC**
Issue [#205](https://github.com/CampusDelSaber/hermes/issues/205) solved

### CODE REVIEW

File: app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java [hunk 1]
```diff
@@ -150,10 +153,13 @@ private void generatePopUpDependingOnTypeUser() {
      * @param point is the coordinate point market.
      */
     public void setReportIncidentStatus(LatLng point) {
-        if (!hasValidStreetContext(point) || isGeneralUser()) {
+        if (!hasValidStreetContext(point)) {
             hideReportIncidentsView();
         } else {
-            showReportIncidentsView();
+            if(UserRepository.getInstance().getUserContained().isAdministrator()){
+                System.out.println("es admin cuando click");
```
Comment (CatCoder36) [inline app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java]: Remember to delete console printouts

**Review by CatCoder36 — COMMENTED** [review]
[Screencast from 02-07-23 19:33:20.webm](https://github.com/CampusDelSaber/hermes/assets/90268595/491bf66c-9464-452d-9efd-bda5be316465)

Persistent bug

File: app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java (hunk 1 above)
Comment (VictorCespedesCC) [reply app/src/main/java/com/isc/hermes/controller/WaypointOptionsController.java]: done

**Review by victor0villca — CHANGES_REQUESTED** [review]
This bug has not been resolved still, which means you can still perform administrative activities like a regular user by following the steps of this issue. Please review your code, again. @VictorCespedesCC

**Review by victor0villca — APPROVED** [review]
The bug is now solved as you can see in the video below:

https://github.com/CampusDelSaber/hermes/assets/135345842/1b13093d-f4e4-4853-bc15-8cbef176d1ee

**Review by CatCoder36 — APPROVED** [review]
Bug solved

File: app/src/main/java/com/isc/hermes/model/Utils/DataAccountOffline.java [hunk 2]
```diff
@@ -53,7 +53,11 @@ public void saveDataLoggedAccount(User user) {
         editor.putString(PATH_IMG_US, user.getPathImageUser());
         editor.putString(USER_TYPE, user.getTypeUser());
 
+        System.out.println("user:" + user.getTypeUser());
```
Comment (mmoralesv) [inline app/src/main/java/com/isc/hermes/model/Utils/DataAccountOffline.java]: Add logging infrastructure methods instead out.println

**Review by mmoralesv — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/isc/hermes/model/Utils/DataAccountOffline.java (hunk 2 above)
Comment (VictorCespedesCC) [reply app/src/main/java/com/isc/hermes/model/Utils/DataAccountOffline.java]: I preferred to delete it, because they were only to be sure of the type of user at a given time.

**Review by denisgandel — APPROVED** [review]

File: app/src/main/java/com/isc/hermes/model/Utils/DataAccountOffline.java (hunk 2 above)
Comment (VictorCespedesCC) [reply app/src/main/java/com/isc/hermes/model/Utils/DataAccountOffline.java]: this printout is not necessary at all, it was only to see in which state the user was saved.

**Review by victor0villca — APPROVED** [review]

**Review by mmoralesv — APPROVED** [review]
