### PR TITLE
Lot of refactorizing

### LINKED ISSUE #114: Bug-436/ Inconsistent Program Functionalities after Logout and Login
**Describe the bug**

During the transition from one activity to another, repeated activities are created and run in the background when a new one is started. and the activity lifecycle is not being properly handled, resulting in unexpected behavior and crashes in the Hermes application

This bug is affecting the customization of styles MapView and the offline Map when navigating between activities.
Requirements

**Prerequisites**
- To have a mobile device
- To have Hermes app installed

**To Reproduce**

1. Execute the Hermes application
2. If you already have an active session, proceed to step 3. Otherwise, you will be presented with the Sign in activity. Sign in with your Gmail account by clicking on the Sign In button.
3. The application will open, displaying the map of your city.
4. Click on the burger button located in the top left corner.
5. A side menu will appear.
6. In the side menu, locate the "Log Out" button.
7. Click on the button to log out.
8. You will be redirected to the login screen.
9. Follow steps 2 to 3 again.
10. In the side menu, click on the button to customize the map style.
11. The side menu will close, and a popup will appear for selecting a different map style.
12. Choose a style different from the one currently displayed in the main activity by clicking on the image style.
13. Popup to select the style will close and The map style of the main activity should change to the one you selected.
14. Take note of the current location shown on the map.
15. Now, click on the burger button again.
16. In the side menu, click on the "Offline Map" button.
17. The Offline Map activity will be displayed.
18. Click on the "Select New Region" button visible in the activity's header.
19. A new window will open, showing the map in the same location where it was left off in the main map activity.
20. Move the screen focus to a different region than the current one.
21. Click "Download" on the bottom button.
22. A popup will open, where you need to provide a name for your region.
23. Click on the "Accept" button in the popup.
24. You will be redirected back to the Offline Map activity.
25. Wait for the region to finish downloading.
26. Once downloaded, click on the three dots on the downloaded map item.
27. A popup will appear, and you should click on "Navigate to"
28. The Offline Map activity will close, and you will be redirected to the Main Activity, centered on the downloaded map region.

**Expected behavior:**
* After logging out and logging in, the program's features such as style customization and the Offline Map should continue to work without any problems.
* The activity lifecycle must be managed correctly, configuration changes must be managed efficiently and the application must behave consistently when resuming from the background.
* Navigation between activities should not cause problems or status changes in the correct functioning of the application.

**Attachment**
bug

**Smartphone:**
 - Device:  Google Pixel 4 
 - Android API 31
 - Android version 11 or higher
 - Google Play Store Services
 
**Additional context**
[Activity Lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle#alc)
To navigate transitions between stages of the activity lifecycle, the Activity class provides a core set of six callbacks: onCreate(), onStart(), onResume(), onPause(), onStop(), and onDestroy(). The system invokes each of these callbacks as the activity enters a new state.

### PR DESCRIPTION
**Pull request by JCarlosHidalgoSosa**
Problems about offline mode not responsive solved, bad performance of map customization and map display class deleted.

### CODE REVIEW

File: app/src/main/java/com/isc/hermes/utils/MapManager.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+    }
+
+    /**
+     * Method to remove current click controller map have
+     */
+    public void removeCurrentClickController() {
+        configurationController.discardFromMap(this.getMapboxMap());
+    }
+
+    public MapboxMap getMapboxMap() {
```
Comment (VillalobosGarciaGaby) [inline app/src/main/java/com/isc/hermes/utils/MapManager.java]: This method needs java docs

Comment (JCarlosHidalgoSosa) [reply app/src/main/java/com/isc/hermes/utils/MapManager.java]: already implemented

**Review by VillalobosGarciaGaby — APPROVED** [review]

**Review by luiggy2620 — APPROVED** [review]

**Review by luiggy-mamani-jalafund — APPROVED** [review]

**Review by daniel-espinoza-79 — APPROVED** [review]
Good Job
